name: profile_card
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  http: ^0.13.3
  googleapis: ^11.4.0
  googleapis_auth: ^3.0.1
  googleapis_calendar: ^2.0.3
  flutter_google_auth: ^3.0.3
  flutter_dotenv: ^5.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.12  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/andres_garcia.jpeg

